# NUMPY Basics 

- NumPy’s main object is the homogeneous multidimensional array.
- NumPy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality.

## Array Attributes

In [12]:

import numpy as np
arr1 = np.arange(15).reshape(3, 5)
print(arr1)
print("\n")
print("Shape = ",arr1.shape)
print("dimensions= ",arr1.ndim)
print("datatype = ",arr1.dtype.name)
print("size = ",arr1.size)
print("class type = ",type(arr1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Shape =  (3, 5)
dimensions=  2
datatype =  int32
size =  15
class type =  <class 'numpy.ndarray'>


In [25]:
def print_arr_attr(arr1):
    print(arr1)
    print("\n\nShape = ",arr1.shape)
    print("dimensions= ",arr1.ndim)
    print("datatype = ",arr1.dtype.name)
    print("size = ",arr1.size)


## Array Creation

In [26]:
# there are several ways you can create arrays
#you can create an array from a regular Python list or tuple using the array function
arr1=np.array([2,3,4]) # provide elements in a single list otherwise it would considered as args for array functions
print_arr_attr(arr1)


[2 3 4]


Shape =  (3,)
dimensions=  1
datatype =  int32
size =  3


In [27]:
# Two Dimensional array - we can call it as sequences of sequences

arr2= np.array([(1,2,3), (4,5,6)])
print_arr_attr(arr2)


[[1 2 3]
 [4 5 6]]


Shape =  (2, 3)
dimensions=  2
datatype =  int32
size =  6


In [28]:
#The type of the array can also be explicitly specified at creation time:

arr3 = np.array( [ [1,2], [3,4] ], dtype=complex )
print_arr_attr(arr3)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


Shape =  (2, 2)
dimensions=  2
datatype =  complex128
size =  4


In [37]:
#Often, the elements of an array are originally unknown, but its size is known. 
#Hence, NumPy offers several functions to create arrays with initial placeholder content. 
#These minimize the necessity of growing arrays, an expensive operation
print("ZEROS")
print(np.zeros( (3,4) ))
print("ONES")
print(np.ones( (3,4) ))
print("EMPTY")
print(np.empty( (5,2) ))
print("Arange - one dimension")
print(np.arange(0,10))
print("Arange - Two dimension")
print(np.arange(0,10).reshape(2,5))

ZEROS
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ONES
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
EMPTY
[[7.54904909e-312 7.54904908e-312]
 [4.86160596e-321             nan]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
Arange - one dimension
[0 1 2 3 4 5 6 7 8 9]
Arange - Two dimension
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
# Create an array with random values
arr = np.random.random((2,2))
print("Array 3 using Random Values = \n", arr)

Array 3 using Random Values = 
 [[0.387492   0.59459825]
 [0.61462435 0.60500785]]


In [151]:
# Create an array of evenly-spaced values
arr = np.linspace(0,2,5)
print("Array 6 using LinSPace = \n", arr)

Array 6 using LinSPace = 
 [0.  0.5 1.  1.5 2. ]


In [152]:
# Create an array using arange function
arr=np.arange(10,25,2)
print("Array 6 using arange() = \n", arr)


Array 6 using arange() = 
 [10 12 14 16 18 20 22 24]


In [153]:
# Create an array of log-spaced values
arr = np.logspace(0,2,9)
print("Array 7 using LOGSPace = \n", arr)

Array 7 using LOGSPace = 
 [  1.           1.77827941   3.16227766   5.62341325  10.
  17.7827941   31.6227766   56.23413252 100.        ]


In [154]:
# Create an array from another array
arr2=np.array(arr)
print("create array using another array = \n", arr2)

create array using another array = 
 [  1.           1.77827941   3.16227766   5.62341325  10.
  17.7827941   31.6227766   56.23413252 100.        ]


## Basic Operations
- Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [47]:
a= np.array([20,30,40,50])
b= np.arange(4)
print("a=",a,"b=",b)
print("a-b")
c= a-b
print(c)

a= [20 30 40 50] b= [0 1 2 3]
a-b
[20 29 38 47]


In [49]:
print("b=",b)
print("b**2 = ",b**2)

b= [0 1 2 3]
b**2 =  [0 1 4 9]


In [51]:
d=np.array([0,45,90,135,180])
print("d=",d)
print("sin a = ",np.sin(d))

d= [  0  45  90 135 180]
sin a =  [ 0.          0.85090352  0.89399666  0.08836869 -0.80115264]


In [53]:
print("a=",a)
print("a<35 =",a<35)

a= [20 30 40 50]
a<35 = [ True  True False False]


In [68]:
#MATRIX Multiplication
#The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:
    
A = np.array([[1,1],[0,1]])   
B = np.array([[2,0],[3,4]])  

print(A)
print(B)
print("A*B does elementwise")
print(A*B)  
    

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
A*B does elementwise
[[2 0]
 [0 4]]


In [71]:
print("dot(A,B) does Matrix Multiplication")
print(np.dot(A,B))
print(A.dot(B))
print(A@B)


dot(A,B) does Matrix Multiplication
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [79]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

a = np.ones((2,3), dtype=int)

b = np.random.random((2,3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.68172599 0.41766698 0.81043608]
 [0.96372927 0.9522775  0.1987239 ]]


In [80]:
a*=3
print(a)

[[3 3 3]
 [3 3 3]]


In [81]:
b+=a
print(b)

[[3.68172599 3.41766698 3.81043608]
 [3.96372927 3.9522775  3.1987239 ]]


In [87]:
#Many unary operations, such as computing the sum of all the elements in the array, 
#are implemented as methods of the ndarray class.
a = np.random.random((2,3))
a
print(a.sum())
print(a.min())
print(a.max())

2.823066786255214
0.017217190766003032
0.9580889577810147


In [96]:
#By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
#However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

b = np.arange(12).reshape(3,4)
print(b)
print("SUM by columnwise")
print(b.sum(axis=0))
    
print("SUM by Rowwise")
print(b.sum(axis=1))
    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
SUM by columnwise
[12 15 18 21]
SUM by Rowwise
[ 6 22 38]


## Universal Functions
-NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal -functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [100]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))


[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


## Aliaing , Deep Copy and View

In [8]:
#  Aliasing the array
import numpy as np
a = np.array([1,2,3,0])
b=a
print(a,b)
a[0]=99

print(a,b)



[1 2 3 0] [1 2 3 0]
[99  2  3  0] [99  2  3  0]


In [9]:
##Deep Copy
a = np.array([1,2,3,0])
b = a.copy()
print("Deep Copy")
print(a)
print(b)
print(b is a)
b[0]=99
print(b)
print(a)

Deep Copy
[1 2 3 0]
[1 2 3 0]
False
[99  2  3  0]
[1 2 3 0]


In [14]:
# creating view
a = np.array([1,2,3,0])
b=a.view() # it is also called as shallow copy.it is different from alias. it has separate memory. 
print(a)
print(b)
b[0]=99
print(a)
print(b)
print(b is a)
print(b.base is a)

[1 2 3 0]
[1 2 3 0]
[99  2  3  0]
[99  2  3  0]
False
True


## Slicing and indexing Numpy Arrays

In [16]:
# arrayname[Start,Stop,StepSize]
a=np.array([10,11,12,13,14,15])
print("array a slice a[1:6:2] is ", a[1:6:2])
print("array a slice a[::] is ", a[::])
print("array a slice a[2:] is ", a[2:])
print("array a slice a[5:2:-1] is ", a[5:2:-1])



array a slice a[1:6:2] is  [11 13 15]
array a slice a[::] is  [10 11 12 13 14 15]
array a slice a[2:] is  [12 13 14 15]
array a slice a[5:2:-1] is  [15 14 13]
